
package service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Apr 16 16:04:54 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "addEvent", namespace = "http://service/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addEvent", namespace = "http://service/")

public class AddEvent {

    @XmlElement(name = "event")
    private model.Event event;

    public model.Event getEvent() {
        return this.event;
    }

    public void setEvent(model.Event newEvent)  {
        this.event = newEvent;
    }

}

